MAIN_URL = 'https://agregatoreat.ru/'
LOGIN_URL = 'https://agregatoreat.ru/lk/supplier'
TRADES_URL = 'https://agregatoreat.ru/purchases/new'
dev_git = 'https://github.com/MalakhovStas'
dev_tm = 'https://t.me/i_am_a_telegram_user'
